blank_issues_enabled: true
contact_links:
  - name: Feedback
    url: https://github.com/orgs/community/discussions
    about: We would love to hear changes you have made or feedback to have to the curriculum
